import {useLocation} from '@hooks';
import {useRoute} from '@react-navigation/native';
import {getDetailUserApi} from '@services';
import {useTheme} from '@theme';
import {UserItemInterface} from '@types';
import {useEffect, useState} from 'react';
import {createStyles} from './styles';
interface DetailUserInterface {
  user: UserItemInterface;
}
export const useDetailUser = () => {
  const router = useRoute();
  const {user} = router.params as DetailUserInterface;
  const [data, setData] = useState(user);
  const {themeColors} = useTheme();
  const styles = createStyles(themeColors);
  const {getDistanceLocation} = useLocation();
  const [games, setGames] = useState([
    {
      id: 4,
      title: 'Call of Duty: Mobile',
      slug: 'call-of-duty-mobile',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 183,
        path: '/uploads/2024/12/31/poster-1.jpg',
        square: '/uploads/2024/12/31/poster-1.jpg',
      },
      banner: {
        id: 183,
        path: '/uploads/2024/12/31/feature-1.jpg',
      },
      like_count: 12,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 14,
            name: 'Chiến lược',
            slug: 'chien-luoc',
            description:
              'Các trò chơi yêu cầu lập kế hoạch và tư duy chiến thuật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 20,
            name: 'Trò chơi ghép hình',
            slug: 'tro-choi-ghep-hinh',
            description: 'Các trò chơi thách thức kỹ năng giải quyết vấn đề.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 281,
            name: 'Phổ biến',
            slug: 'pho-bien',
            description: 'Những trò chơi phổ biến nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 284,
            name: 'Đang thịnh hành',
            slug: 'dang-thinh-hanh',
            description: 'Những trò chơi đang thịnh hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 5,
      title: 'PUBG Mobile',
      slug: 'pubg-mobile',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 184,
        path: '/uploads/2024/12/31/poster-2.jpg',
        square: '/uploads/2024/12/31/poster-2.jpg',
      },
      banner: {
        id: 184,
        path: '/uploads/2024/12/31/feature-2.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 8,
            name: 'Nhập vai',
            slug: 'nhap-vai',
            description:
              'Các trò chơi mà người chơi nhập vai vào các nhân vật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 17,
            name: 'Thể thao',
            slug: 'the-thao',
            description: 'Các trò chơi mô phỏng việc chơi thể thao.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 275,
            name: 'Xếp hạng cao',
            slug: 'xep-hang-cao',
            description: 'Những trò chơi được xếp hạng cao nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 6,
      title: 'Mobile Legends: Bang Bang',
      slug: 'mobile-legends-bang-bang',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 185,
        path: '/uploads/2024/12/31/poster-3.jpg',
        square: '/uploads/2024/12/31/poster-3.jpg',
      },
      banner: {
        id: 185,
        path: '/uploads/2024/12/31/feature-3.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 5,
            name: 'Phiêu lưu',
            slug: 'phieu-luu',
            description: 'Các trò chơi nhấn mạnh vào khám phá và cốt truyện.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 17,
            name: 'Thể thao',
            slug: 'the-thao',
            description: 'Các trò chơi mô phỏng việc chơi thể thao.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 278,
            name: 'Phát hành mới',
            slug: 'phat-hanh-moi',
            description: 'Những trò chơi mới được phát hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 284,
            name: 'Đang thịnh hành',
            slug: 'dang-thinh-hanh',
            description: 'Những trò chơi đang thịnh hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 7,
      title: 'Genshin Impact',
      slug: 'genshin-impact',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 186,
        path: '/uploads/2024/12/31/poster-4.jpg',
        square: '/uploads/2024/12/31/poster-4.jpg',
      },
      banner: {
        id: 186,
        path: '/uploads/2024/12/31/feature-4.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 17,
            name: 'Thể thao',
            slug: 'the-thao',
            description: 'Các trò chơi mô phỏng việc chơi thể thao.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 29,
            name: 'Hộp cát',
            slug: 'hop-cat',
            description:
              'Các trò chơi cung cấp khám phá thế giới mở và sự sáng tạo.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 275,
            name: 'Xếp hạng cao',
            slug: 'xep-hang-cao',
            description: 'Những trò chơi được xếp hạng cao nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 284,
            name: 'Đang thịnh hành',
            slug: 'dang-thinh-hanh',
            description: 'Những trò chơi đang thịnh hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 8,
      title: 'Among Us',
      slug: 'among-us',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 187,
        path: '/uploads/2024/12/31/poster-5.jpg',
        square: '/uploads/2024/12/31/poster-5.jpg',
      },
      banner: {
        id: 187,
        path: '/uploads/2024/12/31/feature-5.jpg',
      },
      like_count: 12,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 8,
            name: 'Nhập vai',
            slug: 'nhap-vai',
            description:
              'Các trò chơi mà người chơi nhập vai vào các nhân vật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 14,
            name: 'Chiến lược',
            slug: 'chien-luoc',
            description:
              'Các trò chơi yêu cầu lập kế hoạch và tư duy chiến thuật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 275,
            name: 'Xếp hạng cao',
            slug: 'xep-hang-cao',
            description: 'Những trò chơi được xếp hạng cao nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 278,
            name: 'Phát hành mới',
            slug: 'phat-hanh-moi',
            description: 'Những trò chơi mới được phát hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 9,
      title: 'Minecraft: Pocket Edition',
      slug: 'minecraft-pocket-edition',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 188,
        path: '/uploads/2024/12/31/poster-6.jpg',
        square: '/uploads/2024/12/31/poster-6.jpg',
      },
      banner: {
        id: 188,
        path: '/uploads/2024/12/31/feature-6.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 2,
            name: 'Hành động',
            slug: 'hanh-dong',
            description:
              'Các trò chơi nhanh nhẹn tập trung vào thử thách vật lý.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 5,
            name: 'Phiêu lưu',
            slug: 'phieu-luu',
            description: 'Các trò chơi nhấn mạnh vào khám phá và cốt truyện.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 8,
            name: 'Nhập vai',
            slug: 'nhap-vai',
            description:
              'Các trò chơi mà người chơi nhập vai vào các nhân vật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 14,
            name: 'Chiến lược',
            slug: 'chien-luoc',
            description:
              'Các trò chơi yêu cầu lập kế hoạch và tư duy chiến thuật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 275,
            name: 'Xếp hạng cao',
            slug: 'xep-hang-cao',
            description: 'Những trò chơi được xếp hạng cao nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 281,
            name: 'Phổ biến',
            slug: 'pho-bien',
            description: 'Những trò chơi phổ biến nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 10,
      title: 'Free Fire',
      slug: 'free-fire',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 189,
        path: '/uploads/2024/12/31/poster-7.jpg',
        square: '/uploads/2024/12/31/poster-7.jpg',
      },
      banner: {
        id: 189,
        path: '/uploads/2024/12/31/feature-7.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 2,
            name: 'Hành động',
            slug: 'hanh-dong',
            description:
              'Các trò chơi nhanh nhẹn tập trung vào thử thách vật lý.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 5,
            name: 'Phiêu lưu',
            slug: 'phieu-luu',
            description: 'Các trò chơi nhấn mạnh vào khám phá và cốt truyện.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 20,
            name: 'Trò chơi ghép hình',
            slug: 'tro-choi-ghep-hinh',
            description: 'Các trò chơi thách thức kỹ năng giải quyết vấn đề.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 29,
            name: 'Hộp cát',
            slug: 'hop-cat',
            description:
              'Các trò chơi cung cấp khám phá thế giới mở và sự sáng tạo.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 278,
            name: 'Phát hành mới',
            slug: 'phat-hanh-moi',
            description: 'Những trò chơi mới được phát hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 284,
            name: 'Đang thịnh hành',
            slug: 'dang-thinh-hanh',
            description: 'Những trò chơi đang thịnh hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 11,
      title: 'Clash of Clans',
      slug: 'clash-of-clans',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 190,
        path: '/uploads/2024/12/31/poster-1.jpg',
        square: '/uploads/2024/12/31/poster-1.jpg',
      },
      banner: {
        id: 190,
        path: '/uploads/2024/12/31/feature-1.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 2,
            name: 'Hành động',
            slug: 'hanh-dong',
            description:
              'Các trò chơi nhanh nhẹn tập trung vào thử thách vật lý.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 5,
            name: 'Phiêu lưu',
            slug: 'phieu-luu',
            description: 'Các trò chơi nhấn mạnh vào khám phá và cốt truyện.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 14,
            name: 'Chiến lược',
            slug: 'chien-luoc',
            description:
              'Các trò chơi yêu cầu lập kế hoạch và tư duy chiến thuật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 278,
            name: 'Phát hành mới',
            slug: 'phat-hanh-moi',
            description: 'Những trò chơi mới được phát hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 284,
            name: 'Đang thịnh hành',
            slug: 'dang-thinh-hanh',
            description: 'Những trò chơi đang thịnh hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 12,
      title: 'Roblox',
      slug: 'roblox',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 191,
        path: '/uploads/2024/12/31/poster-2.jpg',
        square: '/uploads/2024/12/31/poster-2.jpg',
      },
      banner: {
        id: 191,
        path: '/uploads/2024/12/31/feature-2.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 5,
            name: 'Phiêu lưu',
            slug: 'phieu-luu',
            description: 'Các trò chơi nhấn mạnh vào khám phá và cốt truyện.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 14,
            name: 'Chiến lược',
            slug: 'chien-luoc',
            description:
              'Các trò chơi yêu cầu lập kế hoạch và tư duy chiến thuật.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 20,
            name: 'Trò chơi ghép hình',
            slug: 'tro-choi-ghep-hinh',
            description: 'Các trò chơi thách thức kỹ năng giải quyết vấn đề.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 29,
            name: 'Hộp cát',
            slug: 'hop-cat',
            description:
              'Các trò chơi cung cấp khám phá thế giới mở và sự sáng tạo.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 281,
            name: 'Phổ biến',
            slug: 'pho-bien',
            description: 'Những trò chơi phổ biến nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 284,
            name: 'Đang thịnh hành',
            slug: 'dang-thinh-hanh',
            description: 'Những trò chơi đang thịnh hành.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
    {
      id: 13,
      title: 'Pokémon GO',
      slug: 'pokemon-go',
      status: 'active',
      rating_count: 0,
      rating_total: 0,
      views: 0,
      feature: {
        id: 192,
        path: '/uploads/2024/12/31/poster-3.jpg',
        square: '/uploads/2024/12/31/poster-3.jpg',
      },
      banner: {
        id: 192,
        path: '/uploads/2024/12/31/feature-3.jpg',
      },
      like_count: 123,
      release_date: '12/12/2003',
      terms: {
        categories: [
          {
            id: 11,
            name: 'Mô phỏng',
            slug: 'mo-phong',
            description:
              'Các trò chơi mô phỏng các hoạt động trong thế giới thực.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
          {
            id: 17,
            name: 'Thể thao',
            slug: 'the-thao',
            description: 'Các trò chơi mô phỏng việc chơi thể thao.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'categories',
            parent: null,
            lang: 'vi',
          },
        ],
        tags: [
          {
            id: 275,
            name: 'Xếp hạng cao',
            slug: 'xep-hang-cao',
            description: 'Những trò chơi được xếp hạng cao nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
          {
            id: 281,
            name: 'Phổ biến',
            slug: 'pho-bien',
            description: 'Những trò chơi phổ biến nhất.',
            posttype: 'game',
            seo_title: '',
            seo_desc: '',
            type: 'tags',
            parent: null,
            lang: 'vi',
          },
        ],
      },
      posttype: 'game',
    },
  ]);

  useEffect(() => {
    callApiDetailUser();
  }, []);
  const callApiDetailUser = async () => {
    const response = await getDetailUserApi(user.id);
    console.log({response});
    setData(response?.data);
  };
  return {data, themeColors, styles, games, getDistanceLocation};
};
