export const dashboardGame = [
  {
    id: 7,
    'name': 'Temple Run',
    type: 'Phiêu lưu',
    'year': 2011,
    'developer': 'Imangi Studios',
    'platforms': ['Android', 'iOS'],
    'description': '<p>Chạy trốn khỏi những con quái vật trong một ngôi đền cổ, thu thập tiền xu và tránh các chướng ngại vật.</p>',
    'rating': 8.7,
    'likes': 950000,
    'views': 45000000,
    'tags': ['Phiêu lưu', 'Hành động'],
    'poster': 'https://upload.wikimedia.org/wikipedia/vi/3/37/Temple_Run_Logo.PNG',
    'images': ['https://upload.wikimedia.org/wikipedia/vi/3/37/Temple_Run_Logo.PNG'],
    link: 'https://poki.com/en/g/temple-run-2',
  },
  {
    id: 8,

    'name': 'Cut the Rope',
    type: 'Giải đố',
    'year': 2010,
    'developer': 'ZeptoLab',
    'platforms': ['Android', 'iOS'],
    'description': '<p>Giải các câu đố để cắt dây và cho chú ếch Om Nom ăn kẹo.</p>',
    'rating': 8.5,
    'likes': 900000,
    'views': 40000000,
    'tags': ['Giải đố'],
    'poster': 'https://upload.wikimedia.org/wikipedia/en/d/d0/Cut_the_Rope_2_cover.jpg',
    'images': ['https://upload.wikimedia.org/wikipedia/en/d/d0/Cut_the_Rope_2_cover.jpg'],
    link: 'https://www.cuttherope.net',
  },
  {
    id: 1,
    'name': 'The Legend of Zelda: Breath of the Wild',
    'year': 2017,
    'developer': 'Nintendo',
    type: 'Phiêu lưu',
    'platforms': ['Nintendo Switch', 'Wii U'],
    'description': `
<div class="description-productdetail content typeList-style">
  <p><span>👌 Mua game Nintendo Switch giá rẻ hơn, tiết kiệm chi phí hơn với chương trình <span style="color:#ff6600"><strong>"Bán đĩa game cũ đổi đĩa game mới"</strong></span> tại nShop. Chi tiết chương trình click vào: <u style="text-decoration:underline"><u style="color:#0000ff; text-decoration:underline"><a target="_blank" rel="noopener noreferrer" title="Chương trình đổi game cũ Nintendo Switch" style="color: rgb(0, 0, 255); text-decoration: underline;" href="https://www.nshop.com.vn/blogs/khuyen-mai/mua-ban-game-nintendo-switch-cu">&lt;Tham khảo&gt;</a></u></u></span></p>
  <h2><span style="color:#008000; font-size:12pt">Cốt truyện tuyệt vời của&nbsp;THE LEGEND OF ZELDA: BREATH OF THE WILD</span></h2>
  <p><strong><span>“Tỉnh giấc sau 100 năm ngủ vùi, Link phải khám phá thế giới hoang dã xung quanh để tìm lại những ký ức đã mất của mình và cứu lấy Hyrule.”</span></strong></p>
  <p><span style="color:#0000ff"><strong>THE LEGEND OF ZELDA: BREATH OF THE WILD</strong></span> là một trong những tựa game hành động phiêu lưu thế giới mở hay nhất từ trước đến nay. Được phát triển bởi Nintendo, game đã nhận được rất nhiều giải thưởng danh giá từ cộng đồng game thủ và giới phê bình.</span></p>
  <h3><span style="color:#0000ff; font-size:12pt"><strong>Hơn 100 Shrines of Trial để khám phá và thám hiểm</strong></span></h3>
  <p><span>Các điện thờ cổ được rải khắp mọi vùng đất, chờ đợi bạn khám phá theo bất kỳ thứ tự nào. Hãy tìm chúng, phá giải những câu đố của điện thờ và nhận lấy phần thưởng tương xứng.</span></p>
</div>
`,
    'rating': 9.7,
    'likes': 800000,
    'views': 30000000,
    'tags': ['Phiêu lưu', 'Hành động', 'Thế giới mở'],
    'poster': 'https://upload.wikimedia.org/wikipedia/vi/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
    'images': ['https://assets.nintendo.com/image/upload/q_auto/f_auto/ncom/software/switch/70010000000025/7137262b5a64d921e193653f8aa0b722925abc5680380ca0e18a5cfd91697f58'],
  },
  {
    id: 2,
    'name': 'God of War (2018)',
    'year': 2018,
    'developer': 'Santa Monica Studio',
    'platforms': ['PlayStation 4', 'PC'],
    'description': '<p>Kratos và con trai Atreus phiêu lưu qua thế giới Bắc Âu, chiến đấu với các thần thoại và khám phá bí mật về quá khứ của mình.</p>',
    'rating': 9.6,
    'likes': 750000,
    'views': 28000000,
    type: 'Hành động',
    'tags': ['Hành động', 'Phiêu lưu', 'Nhập vai'],
    'poster': 'https://m.media-amazon.com/images/M/MV5BNjJiNTFhY2QtNzZkYi00MDNiLWEzNGEtNWE1NzBkOWIxNmY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSalwQaclD-8DF_An3z6DmqG0oFLLoU-ZwOAQ&s'],
  },
  {
    id: 3,
    'name': 'Elden Ring',
    'year': 2022,
    'type': 'Hành động',
    'developer': 'FromSoftware',
    'platforms': ['PlayStation', 'Xbox', 'PC'],
    'description': '<p>Một thế giới mở rộng lớn với các thử thách khắc nghiệt, nơi người chơi khám phá The Lands Between để khôi phục Elden Ring.</p>',
    'rating': 9.8,
    'likes': 900000,
    'views': 35000000,
    'tags': ['Hành động', 'Nhập vai', 'Thế giới mở'],
    'poster': 'https://upload.wikimedia.org/wikipedia/vi/b/b9/Elden_Ring_Box_art.jpg',
    'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwGhXc6Fphd0bgWQuwtmOqpU837RVsiDzpJQ&s'],
  },
  {
    id: 4,
    'name': 'Cyberpunk 2077',
    'year': 2020,
    'type': 'Hành động',
    'developer': 'CD Projekt Red',
    'platforms': ['PlayStation', 'Xbox', 'PC'],
    'description': '<p>Thành phố Night City, một thế giới tương lai nơi người chơi nhập vai vào V, một lính đánh thuê săn lùng bí mật bất tử.</p>',
    'rating': 8.5,
    'likes': 650000,
    'views': 27000000,
    'tags': ['Hành động', 'Nhập vai', 'Thế giới mở'],
    'poster': 'https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg',
    'images': ['https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg'],
  },
  {
    id: 5,
    'name': 'Red Dead Redemption 2',
    'year': 2018,
    'type': 'Hành động',
    'developer': 'Rockstar Games',
    'platforms': ['PlayStation', 'Xbox', 'PC'],
    'description': '<p>Câu chuyện về Arthur Morgan và băng đảng Van der Linde trong thế giới phương Tây rộng lớn và sống động.</p>',
    'rating': 9.5,
    'likes': 780000,
    'views': 32000000,
    'tags': ['Hành động', 'Phiêu lưu', 'Thế giới mở'],
    'poster': 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
    'images': ['https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg'],
  },
  {
    id: 6,
    'name': 'Subway Surfers',
    type: 'Phiêu lưu',
    'year': 2012,
    'developer': 'Kiloo, SYBO Games',
    'platforms': ['Android', 'iOS'],
    'description': '<p>Chạy trốn khỏi thanh tra khó tính và chú chó của ông ta trong một cuộc phiêu lưu không ngừng nghỉ trên đường ray tàu điện ngầm.</p>',
    'rating': 8.9,
    'likes': 1000000,
    'views': 50000000,
    'tags': ['Phiêu lưu', 'Hành động'],
    'poster': 'https://upload.wikimedia.org/wikipedia/en/5/50/Subway_Surfers_app_icon.png',
    'images': ['https://upload.wikimedia.org/wikipedia/en/5/5e/Subway_Surfers_app_icon.png'],
  },

];
export const gameCategories = [
  {
    id: '1',
    name: 'Kinh dị',
    description: 'Những trò chơi rùng rợn, đầy thử thách và hấp dẫn.',
    image: 'https://img.pikbest.com/png-images/20241012/halloween-hooded-horror-logo_10952776.png!w700wp',
  },
  {
    id: '2',
    name: 'Nhập vai',
    description: 'Trải nghiệm thế giới sống động trong vai trò nhân vật chính.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8UP2THE-5aHU6-bj5YG1Cocb6GVRNzixk0A&s',
  },
  {
    id: '3',
    name: 'Phiêu lưu',
    description: 'Khám phá những vùng đất mới đầy kỳ thú.',
    image: 'https://png.pngtree.com/png-vector/20220527/ourmid/pngtree-rock-climbing-logo-adventure-logo-mountain-mountaineering-vector-png-image_46624924.jpg',
  },
  {
    id: '4',
    name: 'Thể thao',
    description: 'Thử thách bản thân qua những trận đấu gay cấn.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzxcpoqOa6WwKRGvwQguQFZsVeejDXfnXFBg&s',
  },
  {
    id: '5',
    name: 'Bắn súng',
    description: 'Hành động nghẹt thở với những trận đấu súng kịch tính.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD4tOCL-p5qgni6c0huBsocEy86mMKvsfnmQ&s',
  },
  {
    id: '6',
    name: 'Đua xe',
    description: 'Tốc độ, kỹ năng và adrenaline trên mọi cung đường.',
    image: 'https://png.pngtree.com/png-vector/20191028/ourlarge/pngtree-motorcycle-racing-logo-vector-racing-motorcycle-logo-on-black-background-superbike-png-image_1908270.jpg',
  },
  {
    id: '7',
    name: 'Giả lập',
    description: 'Trải nghiệm các tình huống mô phỏng thực tế.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDoZJlhzS2JiurD-HlRRxmUpI7XWnSNMa-yA&s',
  },
  {
    id: '8',
    name: 'Đá bóng',
    description: 'Cảm giác cuồng nhiệt của môn thể thao vua.',
    image: 'https://makan.vn/wp-content/uploads/2022/11/logo-da-banh-vector-1.jpg',
  },
  {
    id: '9',
    name: 'Giải trí',
    description: 'Những trò chơi nhẹ nhàng, thư giãn cho mọi lứa tuổi.',
    image: 'https://thietkelogodep.com.vn/wp-content/uploads/2014/12/LOGO-41.png',
  },
];
