import { API_ENDPOINTS, apiService } from '@api';


export const dashboardHome = [
  {
    id: 1,
    type: 'dating',

  },
  {
    id: 2,
    type: 'movies',
    typeList: 'category',
    name: 'Thư viện phim hay',
    data: [
      {
        id: 1,
        name: 'The Shawshank Redemption',
        year: 1994,
        rating: 9.2,
        category: 1,
        duration: '2h 22min',
        genres: ['Drama'],
        likes: 1,
        views: 100000,
        poster:
          'https://vcdn1-giaitri.vnecdn.net/2022/03/31/shawshank-redemption-137394414-7901-5918-1648713782.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=NHDalOvuyN33Ug53_kOC2Q',
        image: ['https://vcdn1-giaitri.vnecdn.net/2022/03/31/shawshank-redemption-137394414-7901-5918-1648713782.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=NHDalOvuyN33Ug53_kOC2Q', 'https://vcdn1-giaitri.vnecdn.net/2022/03/31/shawshank-redemption-137394414-7901-5918-1648713782.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=NHDalOvuyN33Ug53_kOC2Q'],
      },
      {
        id: 2,
        name: 'The Godfather',
        year: 1972,
        rating: 9.1,
        category: 1,
        duration: '2h 55min',
        genres: ['Crime', 'Drama'],
        likes: 1,
        views: 100000,
        poster: 'https://www.hoasen.edu.vn/wp-content/uploads/2021/11/29a-the-godfather-1972.jpg',
        image: ['https://www.hoasen.edu.vn/wp-content/uploads/2021/11/29a-the-godfather-1972.jpg', 'https://www.hoasen.edu.vn/wp-content/uploads/2021/11/29a-the-godfather-1972.jpg'],
      },
      {
        id: 3,
        name: 'The Dark Knight',
        year: 2008,
        rating: 9.0,
        category: 1,
        duration: '2h 32min',
        genres: ['Action', 'Crime', 'Drama'],
        likes: 1,
        views: 100000,
        poster: 'https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
        image: ['https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
        ],
      },
    ],
  },

  {
    id: 3,
    type: 'movies',
    typeList: 'slider',
    name: 'Thể loại yêu được ưu thích',
    data: [
      {
        id: 1,
        name: 'Hành động',
        data: [
          {
            id: 1,
            name: 'The Dark Knight',
            year: 2008,
            rating: 9.0,
            category: 1,
            duration: '2h 32min',
            genres: ['Action', 'Crime', 'Drama'],
            likes: 1,
            views: 100000,
            poster: 'https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            image: ['https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            ],
          },
          {
            id: 2,
            name: 'The Dark Knight',
            year: 2008,
            rating: 9.0,
            category: 1,
            duration: '2h 32min',
            genres: ['Action', 'Crime', 'Drama'],
            likes: 1,
            views: 100000,
            poster: 'https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            image: ['https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            ],
          },
          {
            id: 3,
            name: 'The Dark Knight',
            year: 2008,
            rating: 9.0,
            category: 1,
            duration: '2h 32min',
            genres: ['Action', 'Crime', 'Drama'],
            likes: 1,
            views: 100000,
            poster: 'https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            image: ['https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            ],
          },
        ],
      },
      {
        id: 1,
        name: 'Phưu lưu',
        data: [
          {
            id: 1,
            name: 'The Dark Knight',
            year: 2008,
            rating: 9.0,
            category: 1,
            duration: '2h 32min',
            genres: ['Action', 'Crime', 'Drama'],
            likes: 1,
            views: 100000,
            poster: 'https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            image: ['https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            ],
          },
          {
            id: 2,
            name: 'The Dark Knight',
            year: 2008,
            rating: 9.0,
            category: 1,
            duration: '2h 32min',
            genres: ['Action', 'Crime', 'Drama'],
            likes: 1,
            views: 100000,
            poster: 'https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            image: ['https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            ],
          },
          {
            id: 3,
            name: 'The Dark Knight',
            year: 2008,
            rating: 9.0,
            category: 1,
            duration: '2h 32min',
            genres: ['Action', 'Crime', 'Drama'],
            likes: 1,
            views: 100000,
            poster: 'https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            image: ['https://play-lh.googleusercontent.com/qhfncXOqccJ5Y_IBPaRy0O79QZQDl7L5FyKQAsLFICt8c9-2Vfmqd2bniAPESto0ZmSLTOzjl-o1F_jgb2Nr',
            ],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    type: 'game',
    typeList: 'category',
    name: 'Game Online',
    data: [
      {
        id: 1,
        'name': 'The Legend of Zelda: Breath of the Wild',
        'year': 2017,
        'developer': 'Nintendo',
        'platforms': ['Nintendo Switch', 'Wii U'],
        'description': '<p>Trở thành Link và phiêu lưu trong thế giới rộng lớn của Hyrule để đánh bại Calamity Ganon và cứu công chúa Zelda.</p>',
        'rating': 9.7,
        'likes': 800000,
        'views': 30000000,
        'category': ['Phiêu lưu', 'Hành động', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/vi/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
        'images': ['https://assets.nintendo.com/image/upload/q_auto/f_auto/ncom/software/switch/70010000000025/7137262b5a64d921e193653f8aa0b722925abc5680380ca0e18a5cfd91697f58'],
      },
      {
        id: 2,
        'name': 'God of War (2018)',
        'year': 2018,
        'developer': 'Santa Monica Studio',
        'platforms': ['PlayStation 4', 'PC'],
        'description': '<p>Kratos và con trai Atreus phiêu lưu qua thế giới Bắc Âu, chiến đấu với các thần thoại và khám phá bí mật về quá khứ của mình.</p>',
        'rating': 9.6,
        'likes': 750000,
        'views': 28000000,
        'category': ['Hành động', 'Phiêu lưu', 'Nhập vai'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BNjJiNTFhY2QtNzZkYi00MDNiLWEzNGEtNWE1NzBkOWIxNmY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSalwQaclD-8DF_An3z6DmqG0oFLLoU-ZwOAQ&s'],
      },
      {
        id: 3,
        'name': 'Elden Ring',
        'year': 2022,
        'developer': 'FromSoftware',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Một thế giới mở rộng lớn với các thử thách khắc nghiệt, nơi người chơi khám phá The Lands Between để khôi phục Elden Ring.</p>',
        'rating': 9.8,
        'likes': 900000,
        'views': 35000000,
        'category': ['Hành động', 'Nhập vai', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/vi/b/b9/Elden_Ring_Box_art.jpg',
        'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwGhXc6Fphd0bgWQuwtmOqpU837RVsiDzpJQ&s'],
      },
      {
        id: 4,
        'name': 'Cyberpunk 2077',
        'year': 2020,
        'developer': 'CD Projekt Red',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Thành phố Night City, một thế giới tương lai nơi người chơi nhập vai vào V, một lính đánh thuê săn lùng bí mật bất tử.</p>',
        'rating': 8.5,
        'likes': 650000,
        'views': 27000000,
        'category': ['Hành động', 'Nhập vai', 'Thế giới mở'],
        'poster': 'https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg',
        'images': ['https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg'],
      },
      {
        id: 5,
        'name': 'Red Dead Redemption 2',
        'year': 2018,
        'developer': 'Rockstar Games',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Câu chuyện về Arthur Morgan và băng đảng Van der Linde trong thế giới phương Tây rộng lớn và sống động.</p>',
        'rating': 9.5,
        'likes': 780000,
        'views': 32000000,
        'category': ['Hành động', 'Phiêu lưu', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
        'images': ['https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg'],
      },
    ],

  },
  {
    id: 5,
    type: 'game',
    typeList: 'list',
    name: 'Nhiều người chơi nhất',
    data: [
      {
        id: 1,
        'name': 'The Legend of Zelda: Breath of the Wild',
        'year': 2017,
        'developer': 'Nintendo',
        'platforms': ['Nintendo Switch', 'Wii U'],
        'description': '<p>Trở thành Link và phiêu lưu trong thế giới rộng lớn của Hyrule để đánh bại Calamity Ganon và cứu công chúa Zelda.</p>',
        'rating': 9.7,
        'likes': 800000,
        'views': 30000000,
        'category': ['Phiêu lưu', 'Hành động', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/vi/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
        'images': ['https://assets.nintendo.com/image/upload/q_auto/f_auto/ncom/software/switch/70010000000025/7137262b5a64d921e193653f8aa0b722925abc5680380ca0e18a5cfd91697f58'],
      },
      {
        id: 2,
        'name': 'God of War (2018)',
        'year': 2018,
        'developer': 'Santa Monica Studio',
        'platforms': ['PlayStation 4', 'PC'],
        'description': '<p>Kratos và con trai Atreus phiêu lưu qua thế giới Bắc Âu, chiến đấu với các thần thoại và khám phá bí mật về quá khứ của mình.</p>',
        'rating': 9.6,
        'likes': 750000,
        'views': 28000000,
        'category': ['Hành động', 'Phiêu lưu', 'Nhập vai'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BNjJiNTFhY2QtNzZkYi00MDNiLWEzNGEtNWE1NzBkOWIxNmY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSalwQaclD-8DF_An3z6DmqG0oFLLoU-ZwOAQ&s'],
      },
      {
        id: 3,
        'name': 'Elden Ring',
        'year': 2022,
        'developer': 'FromSoftware',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Một thế giới mở rộng lớn với các thử thách khắc nghiệt, nơi người chơi khám phá The Lands Between để khôi phục Elden Ring.</p>',
        'rating': 9.8,
        'likes': 900000,
        'views': 35000000,
        'category': ['Hành động', 'Nhập vai', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/vi/b/b9/Elden_Ring_Box_art.jpg',
        'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwGhXc6Fphd0bgWQuwtmOqpU837RVsiDzpJQ&s'],
      },
      {
        id: 4,
        'name': 'Cyberpunk 2077',
        'year': 2020,
        'developer': 'CD Projekt Red',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Thành phố Night City, một thế giới tương lai nơi người chơi nhập vai vào V, một lính đánh thuê săn lùng bí mật bất tử.</p>',
        'rating': 8.5,
        'likes': 650000,
        'views': 27000000,
        'category': ['Hành động', 'Nhập vai', 'Thế giới mở'],
        'poster': 'https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg',
        'images': ['https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg'],
      },
      {
        id: 5,
        'name': 'Red Dead Redemption 2',
        'year': 2018,
        'developer': 'Rockstar Games',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Câu chuyện về Arthur Morgan và băng đảng Van der Linde trong thế giới phương Tây rộng lớn và sống động.</p>',
        'rating': 9.5,
        'likes': 780000,
        'views': 32000000,
        'category': ['Hành động', 'Phiêu lưu', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
        'images': ['https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg'],
      },
    ],
  },
  {
    id: 4,
    type: 'story',
    name: 'Truyên tranh',
    typeList: 'category',
    data: [
      {
        id: 1,
        'name': 'Attack on Titan',
        'year': 2013,
        'director': 'Hajime Isayama',
        'main_characters': ['Eren Yeager', 'Mikasa Ackerman', 'Armin Arlert'],
        'description': '<p>Trong một thế giới bị thống trị bởi những Titan khổng lồ, Eren Yeager và bạn bè của mình chiến đấu để giành lại tự do cho nhân loại.</p>',
        'rating': 9.1,
        'likes': 500000,
        'views': 20000000,
        'category': ['Hành động', 'Kịch tính', 'Giả tưởng'],
        'poster': 'https://pibook.vn/upload/products/attack-on-titan-tap-4.jpg',
        'images': ['https://static2.vieon.vn/vieplay-image/thumbnail_v4/2022/04/20/3k1occft_1920x1080-attackontitan-1.jpg'],
      },
      {
        id: 2,
        'name': 'Demon Slayer: Kimetsu no Yaiba',
        'year': 2019,
        'director': 'Koyoharu Gotouge',
        'main_characters': ['Tanjiro Kamado', 'Nezuko Kamado', 'Zenitsu Agatsuma'],
        'description': '<p>Tanjiro Kamado bắt đầu hành trình trở thành diệt quỷ để cứu em gái mình, Nezuko, khỏi lời nguyền quỷ.</p>',
        'rating': 8.7,
        'likes': 450000,
        'views': 18000000,
        'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
        'poster': 'https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg',
        'images': ['https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg'],
      },
      {
        id: 3,
        'name': 'One Piece',
        'year': 1999,
        'director': 'Eiichiro Oda',
        'main_characters': ['Monkey D. Luffy', 'Roronoa Zoro', 'Nami'],
        'description': '<p>Monkey D. Luffy và nhóm hải tặc Mũ Rơm phiêu lưu qua Grand Line để tìm kho báu huyền thoại One Piece và trở thành Vua Hải Tặc.</p>',
        'rating': 9.0,
        'likes': 700000,
        'views': 25000000,
        'category': ['Hành động', 'Phiêu lưu', 'Hài hước'],
        'poster': 'https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg',
        'images': ['https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg'],
      },
      {
        id: 4,
        'name': 'Naruto',
        'year': 2002,
        'director': 'Masashi Kishimoto',
        'main_characters': ['Naruto Uzumaki', 'Sasuke Uchiha', 'Sakura Haruno'],
        'description': '<p>Naruto Uzumaki là một ninja trẻ tuổi với ước mơ trở thành Hokage để được mọi người công nhận và bảo vệ ngôi làng của mình.</p>',
        'rating': 8.6,
        'likes': 600000,
        'views': 23000000,
        'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        'images': ['https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg'],
      },
    ],
  },
  {
    id: 6,
    type: 'story',
    typeList: 'list',
    name: 'Nhiều người đọc',
    data: [
      {
        id: 1,
        'name': 'Attack on Titan',
        'year': 2013,
        'director': 'Hajime Isayama',
        'main_characters': ['Eren Yeager', 'Mikasa Ackerman', 'Armin Arlert'],
        'description': '<p>Trong một thế giới bị thống trị bởi những Titan khổng lồ, Eren Yeager và bạn bè của mình chiến đấu để giành lại tự do cho nhân loại.</p>',
        'rating': 9.1,
        'likes': 500000,
        'views': 20000000,
        'category': ['Hành động', 'Kịch tính', 'Giả tưởng'],
        'poster': 'https://pibook.vn/upload/products/attack-on-titan-tap-4.jpg',
        'images': ['https://static2.vieon.vn/vieplay-image/thumbnail_v4/2022/04/20/3k1occft_1920x1080-attackontitan-1.jpg'],
      },
      {
        id: 2,
        'name': 'Demon Slayer: Kimetsu no Yaiba',
        'year': 2019,
        'director': 'Koyoharu Gotouge',
        'main_characters': ['Tanjiro Kamado', 'Nezuko Kamado', 'Zenitsu Agatsuma'],
        'description': '<p>Tanjiro Kamado bắt đầu hành trình trở thành diệt quỷ để cứu em gái mình, Nezuko, khỏi lời nguyền quỷ.</p>',
        'rating': 8.7,
        'likes': 450000,
        'views': 18000000,
        'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
        'poster': 'https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg',
        'images': ['https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg'],
      },
      {
        id: 3,
        'name': 'One Piece',
        'year': 1999,
        'director': 'Eiichiro Oda',
        'main_characters': ['Monkey D. Luffy', 'Roronoa Zoro', 'Nami'],
        'description': '<p>Monkey D. Luffy và nhóm hải tặc Mũ Rơm phiêu lưu qua Grand Line để tìm kho báu huyền thoại One Piece và trở thành Vua Hải Tặc.</p>',
        'rating': 9.0,
        'likes': 700000,
        'views': 25000000,
        'category': ['Hành động', 'Phiêu lưu', 'Hài hước'],
        'poster': 'https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg',
        'images': ['https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg'],
      },
      {
        id: 4,
        'name': 'Naruto',
        'year': 2002,
        'director': 'Masashi Kishimoto',
        'main_characters': ['Naruto Uzumaki', 'Sasuke Uchiha', 'Sakura Haruno'],
        'description': '<p>Naruto Uzumaki là một ninja trẻ tuổi với ước mơ trở thành Hokage để được mọi người công nhận và bảo vệ ngôi làng của mình.</p>',
        'rating': 8.6,
        'likes': 600000,
        'views': 23000000,
        'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        'images': ['https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg'],
      },
    ],
  },
];
interface UserProfile {
  id: string;
  avatar: string;
  email: string;
  first_name: string;
  last_name: string;
}
export const getUserProfile = () => {
  return apiService.get<UserProfile>(`${API_ENDPOINTS.USER_PROFILE}`);
};
