export const dashboardSearch = [
  {
    id: 1,
    name: 'Phim đang hot 🔥',
    type: 'MOVIES',
    data: [
      {
        id: 1,
        'name': 'John Wick',
        'year': 2023,
        'director': 'Chad Stahelski',
        type: 'series',
        isLike: true,
        isFavorite: false,
        isWatched: false,
        'main_actors': ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård'],
        'description': '<p>John Wick đối mặt với Hội Đồng Tối Cao trong cuộc chiến cuối cùng để giành lấy tự do. Những màn hành động mãn nhãn và kỹ thuật chiến đấu đỉnh cao tiếp tục đưa khán giả vào một hành trình đầy căng thẳng.</p>',
        'rating': 8.2,
        'likes': 350000,
        'views': 12000000,
        release_date: '2023-03-24',
        'tags': ['Hành động', 'Kịch tính'],
        'poster': 'https://play-lh.googleusercontent.com/yngfkXYS5O2pJZoFHVvHmC5SQPCmzAsEomJv9J_vwWGxvR6nFTyDyaXsimY8w_21tjqVR5pPCKDxT-IR2fs',
        'images': ['https://i.ytimg.com/vi/qEVUtrk8_B4/maxresdefault.jpg'],
        episodes: [
          {
            id: 1,
            name: 'Chapter 1',
            duration: '2h 49m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 2,
            name: 'Chapter 2',
            duration: '2h 43m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 3,
            name: 'Chapter 3',
            duration: '2h 56m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 4,
            name: 'Chapter 4',
            duration: '2h 11m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 5,
            name: 'Chapter 1',
            duration: '2h 49m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 6,
            name: 'Chapter 2',
            duration: '2h 43m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 7,
            name: 'Chapter 3',
            duration: '2h 56m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 8,
            name: 'Chapter 4',
            duration: '2h 11m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 9,
            name: 'Chapter 1',
            duration: '2h 49m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 10,
            name: 'Chapter 2',
            duration: '2h 43m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 11,
            name: 'Chapter 3',
            duration: '2h 56m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 12,
            name: 'Chapter 4',
            duration: '2h 11m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 13,
            name: 'Chapter 1',
            duration: '2h 49m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 14,
            name: 'Chapter 2',
            duration: '2h 43m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 15,
            name: 'Chapter 3',
            duration: '2h 56m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
          {
            id: 16,
            name: 'Chapter 4',
            duration: '2h 11m',
            link: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
          },
        ],
        totalEpisodes: 16,
        currentEpisode: 1,
      },
      {
        id: 2,
        'name': 'Mission: Impossible - Dead Reckoning Part One',
        'year': 2023,
        'director': 'Christopher McQuarrie',
        type: 'movie',
        isLike: true,
        isFavorite: false,
        isWatched: false,
        'main_actors': ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames'],
        'description': '<p>Ethan Hunt và nhóm của anh phải đối đầu với một kẻ thù công nghệ cao, một nhiệm vụ nguy hiểm đẩy họ đến giới hạn.</p>',
        'rating': 8.1,
        'likes': 290000,
        'views': 9800000,
        'tags': ['Hành động', 'Phiêu lưu', 'Gián điệp'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BN2U4OTdmM2QtZTkxYy00ZmQyLTg2N2UtMDdmMGJmNDhlZDU1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAU3SOD3zkFZR4n4CD5wsZAVejgFxg9p8A8g&s'],
      },
      {
        id: 3,
        'name': 'The Batman',
        'year': 2022,
        'director': 'Matt Reeves',
        type: 'movie',
        isLike: true,
        isFavorite: false,
        isWatched: false,
        'main_actors': ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano'],
        'description': '<p>Batman đối mặt với The Riddler, kẻ gieo rắc nỗi kinh hoàng tại Gotham, trong khi khám phá ra bí mật đen tối về gia đình Wayne.</p>',
        'rating': 7.9,
        'likes': 400000,
        'views': 15000000,
        'tags': ['Hành động', 'Tội phạm', 'Kịch tính'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BMmU5NGJlMzAtMGNmOC00YjJjLTgyMzUtNjAyYmE4Njg5YWMyXkEyXkFqcGc@._V1_.jpg',
        'images': ['https://lenaandfilms.wordpress.com/wp-content/uploads/2022/03/desktopbanner.jpg'],
      },
      {
        id: 4,
        'name': 'Top Gun: Maverick',
        'year': 2022,
        'director': 'Joseph Kosinski',
        'main_actors': ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'],
        'description': "<p>Pete 'Maverick' Mitchell trở lại và dẫn dắt thế hệ phi công trẻ trong một nhiệm vụ nguy hiểm chưa từng có.</p>",
        'rating': 8.3,
        'likes': 450000,
        'views': 18000000,
        'category': ['Hành động', 'Kịch tính'],
        'poster': 'https://upload.wikimedia.org/wikipedia/vi/thumb/1/1c/Top_Gun_Maverick_Poster_VN.jpg/220px-Top_Gun_Maverick_Poster_VN.jpg',
        'images': ['https://sdw.sony-asia.com/VN/UserImages/SVN/869_Topgunngang.jpg'],
      },
    ],
  },
  {
    id: 2,
    name: 'Đầu truyện hot 🔥',
    type: 'CHAPTERS',
    data: [
      {
        id: 1,
        'name': 'Attack on Titan',
        'year': 2013,
        'director': 'Hajime Isayama',
        'main_characters': ['Eren Yeager', 'Mikasa Ackerman', 'Armin Arlert'],
        'description': '<p>Trong một thế giới bị thống trị bởi những Titan khổng lồ, Eren Yeager và bạn bè của mình chiến đấu để giành lại tự do cho nhân loại.</p>',
        'rating': 9.1,
        'likes': 500000,
        'views': 20000000,
        'category': ['Hành động', 'Kịch tính', 'Giả tưởng'],
        'poster': 'https://pibook.vn/upload/products/attack-on-titan-tap-4.jpg',
        'images': ['https://static2.vieon.vn/vieplay-image/thumbnail_v4/2022/04/20/3k1occft_1920x1080-attackontitan-1.jpg'],
      },
      {
        id: 2,
        'name': 'Demon Slayer: Kimetsu no Yaiba',
        'year': 2019,
        'director': 'Koyoharu Gotouge',
        'main_characters': ['Tanjiro Kamado', 'Nezuko Kamado', 'Zenitsu Agatsuma'],
        'description': '<p>Tanjiro Kamado bắt đầu hành trình trở thành diệt quỷ để cứu em gái mình, Nezuko, khỏi lời nguyền quỷ.</p>',
        'rating': 8.7,
        'likes': 450000,
        'views': 18000000,
        'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
        'poster': 'https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg',
        'images': ['https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg'],
      },
      {
        id: 3,
        'name': 'One Piece',
        'year': 1999,
        'director': 'Eiichiro Oda',
        'main_characters': ['Monkey D. Luffy', 'Roronoa Zoro', 'Nami'],
        'description': '<p>Monkey D. Luffy và nhóm hải tặc Mũ Rơm phiêu lưu qua Grand Line để tìm kho báu huyền thoại One Piece và trở thành Vua Hải Tặc.</p>',
        'rating': 9.0,
        'likes': 700000,
        'views': 25000000,
        'category': ['Hành động', 'Phiêu lưu', 'Hài hước'],
        'poster': 'https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg',
        'images': ['https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg'],
      },
      {
        id: 4,
        'name': 'Naruto',
        'year': 2002,
        'director': 'Masashi Kishimoto',
        'main_characters': ['Naruto Uzumaki', 'Sasuke Uchiha', 'Sakura Haruno'],
        'description': '<p>Naruto Uzumaki là một ninja trẻ tuổi với ước mơ trở thành Hokage để được mọi người công nhận và bảo vệ ngôi làng của mình.</p>',
        'rating': 8.6,
        'likes': 600000,
        'views': 23000000,
        'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        'images': ['https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg'],
      },
    ],
  },
  {
    id: 3,
    name: 'Game nổi bật',
    type: 'GAMES',
    data: [
      {
        id: 1,
        'name': 'The Legend of Zelda: Breath of the Wild',
        'year': 2017,
        'developer': 'Nintendo',
        'platforms': ['Nintendo Switch', 'Wii U'],
        'description': '<p>Trở thành Link và phiêu lưu trong thế giới rộng lớn của Hyrule để đánh bại Calamity Ganon và cứu công chúa Zelda.</p>',
        'rating': 9.7,
        'likes': 800000,
        'views': 30000000,
        'category': ['Phiêu lưu', 'Hành động', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/vi/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
        'images': ['https://assets.nintendo.com/image/upload/q_auto/f_auto/ncom/software/switch/70010000000025/7137262b5a64d921e193653f8aa0b722925abc5680380ca0e18a5cfd91697f58'],
      },
      {
        id: 2,
        'name': 'God of War (2018)',
        'year': 2018,
        'developer': 'Santa Monica Studio',
        'platforms': ['PlayStation 4', 'PC'],
        'description': '<p>Kratos và con trai Atreus phiêu lưu qua thế giới Bắc Âu, chiến đấu với các thần thoại và khám phá bí mật về quá khứ của mình.</p>',
        'rating': 9.6,
        'likes': 750000,
        'views': 28000000,
        'category': ['Hành động', 'Phiêu lưu', 'Nhập vai'],
        'poster': 'https://m.media-amazon.com/images/M/MV5BNjJiNTFhY2QtNzZkYi00MDNiLWEzNGEtNWE1NzBkOWIxNmY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSalwQaclD-8DF_An3z6DmqG0oFLLoU-ZwOAQ&s'],
      },
      {
        id: 3,
        'name': 'Elden Ring',
        'year': 2022,
        'developer': 'FromSoftware',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Một thế giới mở rộng lớn với các thử thách khắc nghiệt, nơi người chơi khám phá The Lands Between để khôi phục Elden Ring.</p>',
        'rating': 9.8,
        'likes': 900000,
        'views': 35000000,
        'category': ['Hành động', 'Nhập vai', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/vi/b/b9/Elden_Ring_Box_art.jpg',
        'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwGhXc6Fphd0bgWQuwtmOqpU837RVsiDzpJQ&s'],
      },
      {
        id: 4,
        'name': 'Cyberpunk 2077',
        'year': 2020,
        'developer': 'CD Projekt Red',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Thành phố Night City, một thế giới tương lai nơi người chơi nhập vai vào V, một lính đánh thuê săn lùng bí mật bất tử.</p>',
        'rating': 8.5,
        'likes': 650000,
        'views': 27000000,
        'category': ['Hành động', 'Nhập vai', 'Thế giới mở'],
        'poster': 'https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg',
        'images': ['https://product.hstatic.net/1000231532/product/cyberpunk_2077_ultimate_edition_ps5_2fc16399fc9e4e25923e7e0c6bafd45f_master.jpg'],
      },
      {
        id: 5,
        'name': 'Red Dead Redemption 2',
        'year': 2018,
        'developer': 'Rockstar Games',
        'platforms': ['PlayStation', 'Xbox', 'PC'],
        'description': '<p>Câu chuyện về Arthur Morgan và băng đảng Van der Linde trong thế giới phương Tây rộng lớn và sống động.</p>',
        'rating': 9.5,
        'likes': 780000,
        'views': 32000000,
        'category': ['Hành động', 'Phiêu lưu', 'Thế giới mở'],
        'poster': 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
        'images': ['https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg'],
      },
    ],
  },
];

export const dataSearch = [
  {
    id: 1,
    'name': 'John Wick: Chapter 4',
    'year': 2023,
    'director': 'Chad Stahelski',
    'main_actors': ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård'],
    'description': '<p>John Wick đối mặt với Hội Đồng Tối Cao trong cuộc chiến cuối cùng để giành lấy tự do. Những màn hành động mãn nhãn và kỹ thuật chiến đấu đỉnh cao tiếp tục đưa khán giả vào một hành trình đầy căng thẳng.</p>',
    'rating': 8.2,
    'likes': 350000,
    'views': 12000000,
    'category': ['Hành động', 'Kịch tính'],
    'poster': 'https://play-lh.googleusercontent.com/yngfkXYS5O2pJZoFHVvHmC5SQPCmzAsEomJv9J_vwWGxvR6nFTyDyaXsimY8w_21tjqVR5pPCKDxT-IR2fs',
    'images': ['https://i.ytimg.com/vi/qEVUtrk8_B4/maxresdefault.jpg'],
    'duration': '2h 49m',
  },
  {
    id: 2,
    'name': 'Mission: Impossible - Dead Reckoning Part One',
    'year': 2023,
    'director': 'Christopher McQuarrie',
    'main_actors': ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames'],
    'description': '<p>Ethan Hunt và nhóm của anh phải đối đầu với một kẻ thù công nghệ cao, một nhiệm vụ nguy hiểm đẩy họ đến giới hạn.</p>',
    'rating': 8.1,
    'likes': 290000,
    'views': 9800000,
    'category': ['Hành động', 'Phiêu lưu', 'Gián điệp'],
    'poster': 'https://m.media-amazon.com/images/M/MV5BN2U4OTdmM2QtZTkxYy00ZmQyLTg2N2UtMDdmMGJmNDhlZDU1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'images': ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAU3SOD3zkFZR4n4CD5wsZAVejgFxg9p8A8g&s'],
    'duration': '2h 43m',
  },
  {
    id: 3,
    'name': 'The Batman',
    'year': 2022,
    'director': 'Matt Reeves',
    'main_actors': ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano'],
    'description': '<p>Batman đối mặt với The Riddler, kẻ gieo rắc nỗi kinh hoàng tại Gotham, trong khi khám phá ra bí mật đen tối về gia đình Wayne.</p>',
    'rating': 7.9,
    'likes': 400000,
    'views': 15000000,
    'category': ['Hành động', 'Tội phạm', 'Kịch tính'],
    'poster': 'https://m.media-amazon.com/images/M/MV5BMmU5NGJlMzAtMGNmOC00YjJjLTgyMzUtNjAyYmE4Njg5YWMyXkEyXkFqcGc@._V1_.jpg',
    'images': ['https://lenaandfilms.wordpress.com/wp-content/uploads/2022/03/desktopbanner.jpg'],
    'duration': '2h 56m',
  },
  {
    id: 4,
    'name': 'Top Gun: Maverick',
    'year': 2022,
    'director': 'Joseph Kosinski',
    'main_actors': ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'],
    'description': "<p>Pete 'Maverick' Mitchell trở lại và dẫn dắt thế hệ phi công trẻ trong một nhiệm vụ nguy hiểm chưa từng có.</p>",
    'rating': 8.3,
    'likes': 450000,
    'views': 18000000,
    'category': ['Hành động', 'Kịch tính'],
    'poster': 'https://upload.wikimedia.org/wikipedia/vi/thumb/1/1c/Top_Gun_Maverick_Poster_VN.jpg/220px-Top_Gun_Maverick_Poster_VN.jpg',
    'images': ['https://sdw.sony-asia.com/VN/UserImages/SVN/869_Topgunngang.jpg'],
    'duration': '2h 11m',
  },
  {
    id: 5,
    'name': 'Attack on Titan',
    'year': 2013,
    'director': 'Hajime Isayama',
    'main_characters': ['Eren Yeager', 'Mikasa Ackerman', 'Armin Arlert'],
    'description': '<p>Trong một thế giới bị thống trị bởi những Titan khổng lồ, Eren Yeager và bạn bè của mình chiến đấu để giành lại tự do cho nhân loại.</p>',
    'rating': 9.1,
    'likes': 500000,
    'views': 20000000,
    'category': ['Hành động', 'Kịch tính', 'Giả tưởng'],
    'poster': 'https://pibook.vn/upload/products/attack-on-titan-tap-4.jpg',
    'images': ['https://static2.vieon.vn/vieplay-image/thumbnail_v4/2022/04/20/3k1occft_1920x1080-attackontitan-1.jpg'],
    'duration': '24m per episode',
  },
  {
    id: 6,
    'name': 'Demon Slayer: Kimetsu no Yaiba',
    'year': 2019,
    'director': 'Koyoharu Gotouge',
    'main_characters': ['Tanjiro Kamado', 'Nezuko Kamado', 'Zenitsu Agatsuma'],
    'description': '<p>Tanjiro Kamado bắt đầu hành trình trở thành diệt quỷ để cứu em gái mình, Nezuko, khỏi lời nguyền quỷ.</p>',
    'rating': 8.7,
    'likes': 450000,
    'views': 18000000,
    'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
    'poster': 'https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg',
    'images': ['https://cdn.popsww.com/blog/sites/2/2022/01/thanh-guom-diet-quy-review.jpg'],
    'duration': '23m per episode',
  },
  {
    id: 7,
    'name': 'One Piece',
    'year': 1999,
    'director': 'Eiichiro Oda',
    'main_characters': ['Monkey D. Luffy', 'Roronoa Zoro', 'Nami'],
    'description': '<p>Monkey D. Luffy và nhóm hải tặc Mũ Rơm phiêu lưu qua Grand Line để tìm kho báu huyền thoại One Piece và trở thành Vua Hải Tặc.</p>',
    'rating': 9.0,
    'likes': 700000,
    'views': 25000000,
    'category': ['Hành động', 'Phiêu lưu', 'Hài hước'],
    'poster': 'https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg',
    'images': ['https://cdn.tuoitre.vn/zoom/700_390/471584752817336320/2024/10/15/one-piece-egg-head-arc-anime-key-art-1728982505821164134226.jpg'],
    'duration': '24m per episode',
  },
  {
    id: 8,
    'name': 'Naruto',
    'year': 2002,
    'director': 'Masashi Kishimoto',
    'main_characters': ['Naruto Uzumaki', 'Sasuke Uchiha', 'Sakura Haruno'],
    'description': '<p>Naruto Uzumaki là một ninja trẻ tuổi với ước mơ trở thành Hokage để được mọi người công nhận và bảo vệ ngôi làng của mình.</p>',
    'rating': 8.6,
    'likes': 600000,
    'views': 23000000,
    'category': ['Hành động', 'Phiêu lưu', 'Siêu nhiên'],
    'poster': 'https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'images': ['https://m.media-amazon.com/images/M/MV5BZTNjOWI0ZTAtOGY1OS00ZGU0LWEyOWYtMjhkYjdlYmVjMDk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg'],
    'duration': '23m per episode',
  },
];
